### ISSUE TITLE
About 'maxAge'

### ISSUE THREAD

**Issue by hezhongfeng** [Secbone/koa-session2#10]
Does it means the time to destroy session?

**Comment by Secbone** [comment]
No, it just set the expire time of cookie. :)

**Comment by hezhongfeng** [comment]
@Secbone 
Thank you!
And I have another issue.
How can I clear the session,I think the session is more and more.

**Comment by Secbone** [comment]
@hezhongfeng You can write your clear code in `destroy` function in `Store`, or set a expire time in your storage.
