### ISSUE TITLE
can't  import store.js

### ISSUE THREAD

**Issue by qingmingsang** [Secbone/koa-session2#11]
import  {Store} from "koa-session2"
这样引不到 Store 文件
然后我是这样引的
import  Store from 'koa-session2/libs/store'

然后extend 的时候还是会报错，只能把store.js 里 的 class Store用es6的 export 导出

**Comment by Secbone** [comment]
我猜你用的是 node6 版本的 session2，node6 版本的是不带 babel 的，只能用原生 node 支持的语法，import 现在还不支持，是 babel 做转换的，所以如果你正在使用 babel 的话，我建议你用 babel（也就是 master ）版本的  :)

**Comment by qingmingsang** [comment]
嗯
