### ISSUE TITLE
Please fix it

### ISSUE THREAD

**Issue by und3fined** [Secbone/koa-session2#2]
``` javascript
node_modules/koa-session2/dist/index.js:125
            var ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(sid) {
                                        ^

ReferenceError: regeneratorRuntime is not defined
```

**Comment by Secbone** [comment]
@KuTi  Do you use `babel-polyfill`?

**Comment by rimmartin** [comment]
Hi, I get this with v 1.0.4 and before with 1.0.3.

koa next and nodejs 6.2.0.  Trying to set up with redis. Should I install Babel anyway?

**Comment by rimmartin** [comment]
Ah, I'm just not understanding this babel thing; looks like it has to do with yet another javascript spec layer

Which one are you using?

**Comment by Secbone** [comment]
@rimmartin  koa next dependents babel ( async/await ),  so you can use this middleware and koa next with `babel-preset-2015` and `babel-preset -stage-0`  :)

**Comment by rimmartin** [comment]
Thank you,

I also tried 

```
npm install --save-dev babel-preset-es2015-node6
npm install --save-dev babel-polyfill
```

which I thought might make it work with V8 in nodejs 6.2 better.  Still get the error but it may be my environment yet. Adding the preset -stage-0 part.  Nothing more needed from koa session2 :-) Thanks for working on koa v2

**Comment by Secbone** [comment]
:)

**Comment by 0cv** [comment]
This forces us however to add the babelPolyfill even so it may not be required for the rest of the project. Eventually using the [transform-runtime](https://babeljs.io/docs/plugins/transform-runtime/) instead could be a more modular alternative.

**Comment by Secbone** [comment]
@Krisa  Great! I will rebuilt it soon!  thanks! 👍

**Comment by 0cv** [comment]
great thanks!
