### ISSUE TITLE
Add connection config in Store.js

### ISSUE THREAD

**Issue by teabore** [Secbone/koa-session2#21]
Store.js uses the default Redis connection.
Add this change to allow custom configuration:

Store.js
```
constructor(opts) {
	super();
	this.redis = new Redis(opts);
}
```

main.js
```
app.use(session({
    store: new Store({
      host: some.host.or.ip
    })
}));
```

**Comment by Secbone** [comment]
@teabore It's just an example to show how to use the `Store`, you can create your own `Store` class in your projects, just `extends Store` and then do whatever you want. :)
