### ISSUE TITLE
how to use it with mongodb

### ISSUE THREAD

**Issue by jackple** [Secbone/koa-session2#33]
Is there a demo

**Comment by Secbone** [comment]
@jackple no demo for MongoDB yet, but it is very similar to Redis demo in `README` docs.
For example, you can replace Redis in `get` method with MongoDB like this:

```javascript
async get(sid) {
        // this just an instance, something like this
        let data = await this.mongo.findOne({sessionid: sid});
        return JSON.parse(data);
}
```

**Comment by jackple** [comment]
@Secbone Thanks! I will try later
