### ISSUE TITLE
如何将js文件的例子转换为typescript，因为在typescript中，this.redis会报错，提示RedisStore不存在redis这个属性 

### ISSUE THREAD

**Issue by chaoxihailing** [Secbone/koa-session2#39]
![image](https://user-images.githubusercontent.com/17508916/30471090-f5c01f78-9a29-11e7-9956-27b45a0f5c01.png)

**Comment by Secbone** [comment]
@chaoxihailing 你需要先定义一下这个属性，比如这样：
```typescript
class RedisStore extends Store {
    private redis: any;
    constructor() {
        this.redis = new Redis()
    }
}
```

**Comment by chaoxihailing** [comment]
嗯，确实不报错了，多问一句，ctx.session.count写成这样没事
     
![image](https://user-images.githubusercontent.com/17508916/30476073-7747056e-9a3b-11e7-8171-88dd91703c57.png)

但是在typescript中，直接写ctx.session.count会报下面的错，
![image](https://user-images.githubusercontent.com/17508916/30476106-9332f792-9a3b-11e7-99ee-36f3b0eeb251.png)

typescript的写法
![image](https://user-images.githubusercontent.com/17508916/30476165-b9e88500-9a3b-11e7-8ce5-4337cee4e453.png)

使用的是koa，在typescript中，如何给session添加属性？

**Comment by chaoxihailing** [comment]
问题解决了，忘记配置模板了
