### ISSUE TITLE
destroy (or destory) not called when ctx.logout is called

### ISSUE THREAD

**Issue by 0cv** [Secbone/koa-session2#4]
Beside the fact the destroy function is currently called destory, neither one nor the other (destory / destroy) seems to get called when the ctx.logout() method is triggered (as part of Koa-Passport). I don't know if it's because the function is currently not called correctly, or whether I'm missing anything else.

**Comment by Secbone** [comment]
It is not support `koa-passport` yet, I think I will support it soon. :)

**Comment by Secbone** [comment]
@Krisa Oh!  I got it!  I will fix it soon! :)
