### ISSUE TITLE
如果session后面，有一条报错的语句，session语句不会执行

### ISSUE THREAD

**Issue by chaoxihailing** [Secbone/koa-session2#40]
![image](https://user-images.githubusercontent.com/17508916/30534748-22c0e74a-9c92-11e7-8f6f-40028dc8ef97.png)

**Comment by chaoxihailing** [comment]
如果取消下面的报错语句，那么session那条语句也可以执行

**Comment by chaoxihailing** [comment]
使用的koa，koa-session2，还有typescript

**Comment by Secbone** [comment]
@chaoxihailing  `koa-session2` 是在中间件返回的阶段设置 session 的，throw error 以后会导致所有后续的中间件都不再执行，详情可以了解一下 `koa` 实现原理

**Comment by chaoxihailing** [comment]
嗯，确实是koa的问题，现在有个新的问题了，有个ip是192.168.10.108，我本机的ip是192.168.10.124（服务器在上面跑），我用ip为192.168.10.108访问我本机的服务，那么每一次点击都会生成新的sessionID，而我本机访问服务器却没有这个问题，这个是跨域的问题？

**Comment by chaoxihailing** [comment]
@Secbone

**Comment by chaoxihailing** [comment]
@Secbone 我发现如果用非本机的浏览器访问，那么服务器会生成sessionID给浏览器，但是在浏览器中sessionID却没有发现它储存了sessionID，这是什么导致的？

服务器返回了sessionId
![image](https://user-images.githubusercontent.com/17508916/30624562-b1026862-9df0-11e7-806f-435afc52a9ef.png)

浏览器中却没有保存
![qq 20170920103627](https://user-images.githubusercontent.com/17508916/30624397-d44b1bee-9def-11e7-8e25-597485885560.png)

**Comment by Secbone** [comment]
@chaoxihailing 这些问题已经不属于 `koa-session2` 中间件的问题了。非常抱歉，工作比较忙，不能帮你 DEBUG... 😞

**Comment by chaoxihailing** [comment]
嗯，没事
