### ISSUE TITLE
Session key from cookie?

### ISSUE THREAD

**Issue by antonsegerkvist** [Secbone/koa-session2#41]
When a session key already exists in the browser and is sent to the server the session key is reused. Is this the indented behaviour?

Best Regards
Anton

**Comment by Secbone** [comment]
@antonsegerkvist  yes, if you didn't refresh the key, it will be reused.

**Comment by antonsegerkvist** [comment]
@Secbone Ok.
Tanks 👍 

Best Regards
Anton
