### ISSUE TITLE
can i comment the line : if(old == JSON.stringify(ctx.session)) return;

### ISSUE THREAD

**Issue by halloffamezwx** [Secbone/koa-session2#44]
can i comment the line?

if(old == JSON.stringify(ctx.session)) return;

**Comment by Secbone** [comment]
@halloffamezwx  why?  Any bugs?

**Comment by halloffamezwx** [comment]
@Secbone i set the maxAge 10 second，and put the user info in the session when login success，during the 10 second period i keep refreshing my website，after 10 second the session still invalid，i had to login again.

i found this line can update the maxAge's timmer , but my session not changed after login success.
// set/update session
const sid = await store.set(ctx.session, Object.assign({}, opts, {sid: id}), ctx);

english not my mother laguage!

**Comment by Secbone** [comment]
@halloffamezwx 我还是没太明白问题在哪里？

**Comment by halloffamezwx** [comment]
@Secbone 就是我做一个登录功能，登录成功后把用户信息设置到session，现在的问题就是，这个session的失效时间我设置为30分钟，然后我在29分钟时请求了我的后台接口，按道理这时候session的失效时间要重新设置为30分钟吧，然而1分钟后session还是失效了，然后我要重新登录了。

**Comment by Secbone** [comment]
@halloffamezwx session 的更新策略是各自自己去实现的，`koa-session2` 这里的失效管理是基于浏览器 Cookie 的，至于你希望用户每次访问的时候更新 session，还是 强制一段时间后失效，是根据自己业务决定的。

目前要做每次访问更新的话，你可以给 session 添加一个时间戳，每次访问后更新时间戳，这样就会生成新的 session id 达到续期的目的。

不过目前这样看确实不是一个好的办法，这个问题我会再想一下解决办法

**Comment by halloffamezwx** [comment]
@Secbone 好的
