### ISSUE TITLE
How to update session

### ISSUE THREAD

**Issue by LeonYanghaha** [Secbone/koa-session2#48]
I used this library to store the session to redis, and I set the expiration time of the session. However, the problem was that the session was not updated in time after refreshing the page, and the session delivery in redis was still the session at the time of login, which did not change with the user's operation. I tried to add the code,`ctx.session.user = player ;` and the session was not updated. Who can tell me how to do it? Thank you very much.

**Comment by LeonYanghaha** [comment]
What I expect is that the session is stored in redis after the user logs in (this is done), and then the user has other operations every time, stores the information of operations in session, and updates redis in time.

**Comment by Secbone** [comment]
@Yangk030208 I'm working on this issue. There is another one who makes the same issue here #44 
I just found a way to resolve it and keep it easy to use, and I will release a new version tonight or tomorrow.  😄

**Comment by LeonYanghaha** [comment]
@
