### ISSUE TITLE
koa2  use koa-session2 how to connection mongodb

### ISSUE THREAD

**Issue by godruoyi** [Secbone/koa-session2#9]
Please help me?

**Comment by Secbone** [comment]
@godruoyi You can put your connection code in the constructor function of your custom store. :)

**Comment by godruoyi** [comment]
i whant use mongodb as session store, but i down't know how to connect it sach as :

``` javascript
//app.js
import session from "koa-session2";
import {Store} from "koa-session2";

......


// here, i whant use mongodb as session store, how to set it ....
app.use(session({
  key: 'settings.sessionkey',
  store: new Store()
}));


```

**Comment by Secbone** [comment]
@godruoyi You can write your class of store with extending koa-session2 store, and write you connection code in the constructor function of the store class, just like [the example in README](https://github.com/Secbone/koa-session2#custom-stores). :)
